project:
  type: website
  output-dir: docs

website:
  title: "RNA-Seq using Nextflow: Day 1"
  navbar:
    background: primary
    left:
      - href: https://sydney-informatics-hub.github.io/training.RNAseq.series-quarto/
        text: Home
      - href: notebooks/0.0_about.html
        text: "About"
      - href: setup.html
        text: "Set-up"
      - text: "Day 1 kick off"
        menu:
        - text: "Learning objectives"
          href: notebooks/1.0_Learning_objectives.html
        - text: "Introductory slides"
          href: https://docs.google.com/presentation/d/1Na2nAlK34N196ONzMazGbpxvd-h7Ltx82webeLlN4RU/edit?usp=sharing
        - text: "Prepare your data"
          href: notebooks/1.1_Download_data.html
        - text: "Run the pipeline"
          href: notebooks/1.2_Running_nfcore_command.html
      - text: "Why use nf-core/rnaseq?"
        menu:
        - text: "Introduction to Nextflow"
          href: notebooks/2.0_intro_to_nextflow_and_nfcore.html
        - text: "Introduction to nf-core/rnaseq"
          href: notebooks/2.1_nfcore-rnaseq.html
        - text: "Customising nf-core/rnaseq"
          href: notebooks/2.2_nfcore-rnaseq_otherImportantParameters.html
      - text: "What is nf-core/rnaseq doing?"
        menu:
        - text: "RNA-seq workflow overview"
          href: notebooks/3.0_The_pipeline.html
        - text: "nf-core/rnaseq results"
          href: notebooks/3.1_Interpreting_results.html
        - text: "Raw sequencing data QC"
          href: notebooks/3.2_fastQ_and_fastQC.html
        - text: "Read trimming"
          href: notebooks/3.3_Trimming.html
        - text: "Read alignment and quantification"
          href: notebooks/3.4_Alignment_using_STAR.html
        - text: "Nextflow logs"
          href: notebooks/3.5_Interpreting_results_2.html
      - text: "Day 1 wrap up"
        href: notebooks/4_Summary_Day1.html
      
  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github




